import { relative } from "node:path";

import {
  readIssueMap,
  resolveRetrospectivePaths,
  writeIssueMap,
} from "./retrospective-artifacts.js";
import { redactRetrospectiveIssueText } from "./retrospective-redaction.js";
import type {
  RetrospectiveFinding,
  RetrospectiveIssueMap,
  RetrospectiveIssueRecord,
  RetrospectiveOutcome,
  RetrospectivePreferences,
} from "./retrospective-types.js";
import {
  ghCreateIssue,
  ghEnsureLabel,
  ghListIssuesByLabel,
  type GhResult,
  type ListedIssue,
} from "../github-sync/cli.js";

const PERSONAL_RETRO_REPO = "skspade/gsd-pi";
const DEFAULT_RETRO_LABEL = "gsd-auto-retro";
const DEFAULT_MAX_ISSUES = 10;

export type RetrospectiveFilingConfig =
  | { enabled: false; reason: string }
  | {
      enabled: true;
      issueRepo: string;
      issueLabel: string;
      maxIssuesPerRun: number;
    };

export interface BuildRetrospectiveIssueBodyInput {
  basePath: string;
  milestoneId: string;
  outcome: RetrospectiveOutcome;
  reason?: string;
  finding: RetrospectiveFinding;
  retroPath: string;
}

export function resolveRetrospectiveFilingConfig(
  prefs: RetrospectivePreferences | undefined,
): RetrospectiveFilingConfig {
  if (!prefs?.enabled) return { enabled: false, reason: "retrospective disabled" };
  if (!prefs.issue_repo) return { enabled: false, reason: "retrospective.issue_repo is not configured" };
  if (prefs.issue_repo === "open-gsd/gsd-pi") {
    return { enabled: false, reason: "retrospective.issue_repo must not target open-gsd/gsd-pi" };
  }
  if (prefs.issue_repo !== PERSONAL_RETRO_REPO) {
    return { enabled: false, reason: "retrospective.issue_repo must be skspade/gsd-pi" };
  }

  return {
    enabled: true,
    issueRepo: prefs.issue_repo,
    issueLabel: prefs.issue_label?.trim() || DEFAULT_RETRO_LABEL,
    maxIssuesPerRun: Math.floor(prefs.max_issues_per_run ?? DEFAULT_MAX_ISSUES),
  };
}

export function buildRetrospectiveIssueTitle(finding: RetrospectiveFinding, basePath = ""): string {
  const title = redactRetrospectiveIssueText(
    `[auto-retro][${finding.category}] ${finding.title}`,
    basePath,
  ).replace(/\s+/g, " ").trim();
  return title.length <= 240 ? title : `${title.slice(0, 237)}...`;
}

export function buildRetrospectiveIssueBody(input: BuildRetrospectiveIssueBodyInput): string {
  const { finding } = input;
  const raw = [
    "## Auto Retrospective Finding",
    "",
    "Auto-generated by GSD milestone retrospective. False positives are acceptable; review via the auto-retro label.",
    "",
    "## Run",
    "",
    `- Milestone: \`${input.milestoneId}\``,
    `- Outcome: \`${input.outcome}\``,
    input.reason ? `- Reason: ${input.reason}` : "- Reason: not recorded",
    `- Local retrospective: \`${input.retroPath}\``,
    "",
    "## Finding",
    "",
    `- Category: \`${finding.category}\``,
    `- Severity: \`${finding.severity}\``,
    `- Confidence: \`${finding.confidence}\``,
    `- Fingerprint: \`${finding.fingerprint}\``,
    "",
    finding.summary,
    "",
    "## Evidence",
    "",
    ...finding.evidence.map((entry) => `- ${entry}`),
    "",
    "## Suggested Fix",
    "",
    finding.suggestedFix,
    "",
    "---",
    "*Auto-generated by GSD milestone retrospective*",
  ].join("\n");

  return redactRetrospectiveIssueText(raw, input.basePath);
}

export function planRetrospectiveIssueFiling(input: {
  findings: RetrospectiveFinding[];
  existingFingerprints: Set<string>;
  maxIssues: number;
}): RetrospectiveFinding[] {
  const planned: RetrospectiveFinding[] = [];
  const seenFingerprints = new Set(input.existingFingerprints);
  const maxIssues = Math.max(0, Math.floor(input.maxIssues));

  for (const finding of input.findings) {
    if (seenFingerprints.has(finding.fingerprint)) continue;
    if (planned.length >= maxIssues) break;
    seenFingerprints.add(finding.fingerprint);
    planned.push(finding);
  }

  return planned;
}

export interface FileRetrospectiveIssuesDeps {
  createIssue?: typeof ghCreateIssue;
  ensureLabel?: typeof ghEnsureLabel;
  listIssuesByLabel?: typeof ghListIssuesByLabel;
}

export interface FileRetrospectiveIssuesInput extends FileRetrospectiveIssuesDeps {
  basePath: string;
  milestoneId: string;
  outcome: RetrospectiveOutcome;
  reason?: string;
  config: Extract<RetrospectiveFilingConfig, { enabled: true }>;
  findings: RetrospectiveFinding[];
}

export interface FileRetrospectiveIssuesResult {
  created: number;
  pending: number;
  skipped: number;
}

function existingFingerprintsFromIssues(result: GhResult<ListedIssue[]>): Set<string> {
  const values = new Set<string>();
  if (!result.ok) return values;

  for (const issue of result.data ?? []) {
    const haystack = `${issue.title}\n${issue.body ?? ""}`;
    for (const match of haystack.matchAll(/\bFingerprint:\s*`?([a-f0-9]{64})`?/gi)) {
      values.add(match[1]!.toLowerCase());
    }
  }

  return values;
}

function countPending(records: RetrospectiveIssueRecord[]): number {
  return records.filter((record) => record.status === "pending").length;
}

function buildRetrospectiveIssueRecord(input: {
  finding: RetrospectiveFinding;
  status: "created" | "pending";
  updatedAt: string;
  issueRepo: string;
  issueNumber?: number;
  error?: string;
  body?: string;
}): RetrospectiveIssueRecord {
  const record: RetrospectiveIssueRecord = {
    fingerprint: input.finding.fingerprint,
    title: input.finding.title,
    category: input.finding.category,
    status: input.status,
    updatedAt: input.updatedAt,
  };
  if (input.issueNumber !== undefined) {
    record.issueNumber = input.issueNumber;
    record.issueUrl = `https://github.com/${input.issueRepo}/issues/${input.issueNumber}`;
  }
  if (input.error) record.error = input.error;
  if (input.body) record.body = input.body;
  return record;
}

function upsertIssueRecord(
  records: RetrospectiveIssueRecord[],
  replacement: RetrospectiveIssueRecord,
): void {
  const index = records.findIndex((record) =>
    record.status === "pending" &&
    record.fingerprint.toLowerCase() === replacement.fingerprint.toLowerCase()
  );
  if (index === -1) {
    records.push(replacement);
  } else {
    records[index] = replacement;
  }
}

export async function fileRetrospectiveIssues(
  input: FileRetrospectiveIssuesInput,
): Promise<FileRetrospectiveIssuesResult> {
  const paths = resolveRetrospectivePaths(input.basePath, input.milestoneId);
  const existingMap = readIssueMap(paths.issueMap);
  const records = existingMap?.records ?? [];
  const existingFingerprints = new Set(
    records
      .filter((record) => record.status !== "pending")
      .map((record) => record.fingerprint.toLowerCase()),
  );

  const listIssuesByLabel = input.listIssuesByLabel ?? ghListIssuesByLabel;
  const remoteIssues = listIssuesByLabel(input.basePath, input.config.issueRepo, input.config.issueLabel, 100);
  for (const fingerprint of existingFingerprintsFromIssues(remoteIssues)) existingFingerprints.add(fingerprint);

  const planned = planRetrospectiveIssueFiling({
    findings: input.findings,
    existingFingerprints,
    maxIssues: input.config.maxIssuesPerRun,
  });

  const nextRecords: RetrospectiveIssueRecord[] = [...records];
  let created = 0;

  const writeResult = () => {
    const map: RetrospectiveIssueMap = {
      version: 1,
      milestoneId: input.milestoneId,
      issueRepo: input.config.issueRepo,
      issueLabel: input.config.issueLabel,
      records: nextRecords,
    };
    writeIssueMap(paths.issueMap, map);

    return {
      created,
      pending: countPending(nextRecords),
      skipped: input.findings.length - planned.length,
    };
  };

  const buildBody = (finding: RetrospectiveFinding): string => buildRetrospectiveIssueBody({
    basePath: input.basePath,
    milestoneId: input.milestoneId,
    outcome: input.outcome,
    reason: input.reason,
    finding,
    retroPath: relative(input.basePath, paths.retro),
  });

  if (!remoteIssues.ok && planned.length > 0) {
    const updatedAt = new Date().toISOString();
    for (const finding of planned) {
      const record = buildRetrospectiveIssueRecord({
        finding,
        status: "pending",
        updatedAt,
        issueRepo: input.config.issueRepo,
        error: `could not list existing retrospective issues: ${remoteIssues.error ?? "unknown error"}`,
        body: buildBody(finding),
      });
      upsertIssueRecord(nextRecords, record);
    }
    return writeResult();
  }

  const ensureLabel = input.ensureLabel ?? ghEnsureLabel;
  if (planned.length > 0) {
    const labelResult = ensureLabel(input.basePath, input.config.issueRepo, input.config.issueLabel);
    if (!labelResult.ok) {
      const updatedAt = new Date().toISOString();
      for (const finding of planned) {
        const record = buildRetrospectiveIssueRecord({
          finding,
          status: "pending",
          updatedAt,
          issueRepo: input.config.issueRepo,
          error: `could not ensure retrospective label: ${labelResult.error ?? "unknown error"}`,
          body: buildBody(finding),
        });
        upsertIssueRecord(nextRecords, record);
      }
      return writeResult();
    }
  }

  const createIssue = input.createIssue ?? ghCreateIssue;

  for (const finding of planned) {
    const body = buildBody(finding);
    const issueResult = createIssue(input.basePath, {
      repo: input.config.issueRepo,
      title: buildRetrospectiveIssueTitle(finding, input.basePath),
      body,
      labels: [input.config.issueLabel],
    });
    const updatedAt = new Date().toISOString();

    if (issueResult.ok) {
      created++;
      const record = buildRetrospectiveIssueRecord({
        finding,
        status: "created",
        updatedAt,
        issueRepo: input.config.issueRepo,
        issueNumber: issueResult.data,
      });
      upsertIssueRecord(nextRecords, record);
    } else {
      const record = buildRetrospectiveIssueRecord({
        finding,
        status: "pending",
        updatedAt,
        issueRepo: input.config.issueRepo,
        error: issueResult.error,
        body,
      });
      upsertIssueRecord(nextRecords, record);
    }
  }

  return writeResult();
}
