import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, realpathSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { readIssueMap, writeIssueMap } from "../retrospective-artifacts.ts";
import {
  buildRetrospectiveIssueBody,
  buildRetrospectiveIssueTitle,
  fileRetrospectiveIssues,
  planRetrospectiveIssueFiling,
  resolveRetrospectiveFilingConfig,
} from "../retrospective-github.ts";
import type { RetrospectiveFinding } from "../retrospective-types.ts";

const fakeGithubClassicToken = `gh${"p"}_1234567890abcdefghijklmnopqrstuvwxyz`;

function makeFinding(overrides: Partial<RetrospectiveFinding> = {}): RetrospectiveFinding {
  return {
    title: "Route ownership was not checked",
    summary: "The first edit targeted a similarly named view instead of the owning route component.",
    category: "workflow-friction",
    severity: "medium",
    confidence: "high",
    evidence: [
      "Route /lineage-explorer uses /Users/seanspade/source/gsd-pi/src/pages/lineage-explorer.tsx.",
      `Authorization: Bearer ${fakeGithubClassicToken}`,
    ],
    suggestedFix: "Grep the route before editing similarly named view files.",
    fingerprint: "a".repeat(64),
    ...overrides,
  };
}

test("resolveRetrospectiveFilingConfig only enables the personal fork", () => {
  assert.deepEqual(resolveRetrospectiveFilingConfig(undefined), { enabled: false, reason: "retrospective disabled" });
  assert.deepEqual(
    resolveRetrospectiveFilingConfig({ enabled: false, issue_repo: "skspade/gsd-pi" }),
    { enabled: false, reason: "retrospective disabled" },
  );
  assert.deepEqual(
    resolveRetrospectiveFilingConfig({ enabled: true }),
    { enabled: false, reason: "retrospective.issue_repo is not configured" },
  );
  assert.deepEqual(
    resolveRetrospectiveFilingConfig({ enabled: true, issue_repo: "open-gsd/gsd-pi" }),
    { enabled: false, reason: "retrospective.issue_repo must not target open-gsd/gsd-pi" },
  );
  assert.deepEqual(
    resolveRetrospectiveFilingConfig({ enabled: true, issue_repo: "someone/gsd-pi" }),
    { enabled: false, reason: "retrospective.issue_repo must be skspade/gsd-pi" },
  );

  assert.deepEqual(
    resolveRetrospectiveFilingConfig({ enabled: true, issue_repo: "skspade/gsd-pi" }),
    {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "gsd-auto-retro",
      maxIssuesPerRun: 10,
    },
  );

  assert.deepEqual(
    resolveRetrospectiveFilingConfig({
      enabled: true,
      issue_repo: "skspade/gsd-pi",
      issue_label: "custom-retro",
      max_issues_per_run: 3,
    }),
    {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "custom-retro",
      maxIssuesPerRun: 3,
    },
  );
});

test("buildRetrospectiveIssueBody includes review context and redacts sensitive text", () => {
  const finding = makeFinding();
  const body = buildRetrospectiveIssueBody({
    basePath: "/Users/seanspade/source/gsd-pi",
    milestoneId: "M042",
    outcome: "completed",
    reason: "Milestone complete",
    finding,
    retroPath: "/Users/seanspade/source/gsd-pi/.gsd/milestones/M042/M042-RETRO.md",
  });

  assert.equal(
    buildRetrospectiveIssueTitle(finding, "/Users/seanspade/source/gsd-pi"),
    "[auto-retro][workflow-friction] Route ownership was not checked",
  );
  assert.match(body, /## Auto Retrospective Finding/);
  assert.match(body, /False positives are acceptable; review via the auto-retro label/);
  assert.match(body, /Milestone: `M042`/);
  assert.match(body, /Outcome: `completed`/);
  assert.match(body, /Reason: Milestone complete/);
  assert.match(body, /Local retrospective: `\.gsd\/milestones\/M042\/M042-RETRO\.md`/);
  assert.match(body, /Category: `workflow-friction`/);
  assert.match(body, /Severity: `medium`/);
  assert.match(body, /Confidence: `high`/);
  assert.match(body, /Fingerprint: `a{64}`/);
  assert.match(body, /The first edit targeted a similarly named view/);
  assert.match(body, /Grep the route before editing similarly named view files/);
  assert.match(body, /<project>\/src\/pages\/lineage-explorer\.tsx/);
  assert.doesNotMatch(body, /\/Users\/seanspade\/source\/gsd-pi/);
  assert.doesNotMatch(body, /ghp_/);
  assert.match(body, /\*Auto-generated by GSD milestone retrospective\*/);
});

test("buildRetrospectiveIssueTitle redacts sensitive title text", () => {
  const title = buildRetrospectiveIssueTitle(
    makeFinding({ title: `Leaked /Users/seanspade/source/gsd-pi/file.ts ${fakeGithubClassicToken}` }),
    "/Users/seanspade/source/gsd-pi",
  );

  assert.match(title, /<project>\/file\.ts/);
  assert.doesNotMatch(title, /\/Users\/seanspade/);
  assert.doesNotMatch(title, /ghp_/);
});

test("planRetrospectiveIssueFiling skips existing and duplicate fingerprints and caps new findings in order", () => {
  const first = makeFinding({ title: "First", fingerprint: "1".repeat(64) });
  const second = makeFinding({ title: "Second", fingerprint: "2".repeat(64) });
  const third = makeFinding({ title: "Third", fingerprint: "3".repeat(64) });
  const fourth = makeFinding({ title: "Fourth", fingerprint: "4".repeat(64) });
  const duplicateFirst = makeFinding({ title: "Duplicate first", fingerprint: first.fingerprint });

  const planned = planRetrospectiveIssueFiling({
    findings: [first, second, duplicateFirst, third, fourth],
    existingFingerprints: new Set([second.fingerprint]),
    maxIssues: 2,
  });

  assert.deepEqual(planned, [first, third]);
});

test("fileRetrospectiveIssues records pending payload when createIssue fails", async () => {
  const base = realpathSync(mkdtempSync(join(tmpdir(), "gsd-retro-file-")));
  mkdirSync(join(base, ".gsd", "milestones", "M001"), { recursive: true });

  const result = await fileRetrospectiveIssues({
    basePath: base,
    milestoneId: "M001",
    outcome: "completed",
    config: {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "gsd-auto-retro",
      maxIssuesPerRun: 10,
    },
    findings: [
      makeFinding({
        title: "Prompt confused two route owners",
        summary: "Prompt confused two route owners during closeout.",
      }),
    ],
    createIssue: () => ({ ok: false, error: "gh not authenticated" }),
    ensureLabel: () => ({ ok: true, data: undefined }),
    listIssuesByLabel: () => ({ ok: true, data: [] }),
  });

  assert.equal(result.created, 0);
  assert.equal(result.pending, 1);
  const map = readIssueMap(join(base, ".gsd", "milestones", "M001", "M001-RETRO-ISSUES.json"));
  assert.equal(map?.records[0]?.status, "pending");
  assert.match(map?.records[0]?.body ?? "", /Prompt confused two route owners/);
});

test("fileRetrospectiveIssues retries pending records and replaces them when creation succeeds", async () => {
  const base = realpathSync(mkdtempSync(join(tmpdir(), "gsd-retro-file-")));
  mkdirSync(join(base, ".gsd", "milestones", "M003"), { recursive: true });
  const pendingFinding = makeFinding({
    title: "Retry me",
    fingerprint: "5".repeat(64),
  });

  await fileRetrospectiveIssues({
    basePath: base,
    milestoneId: "M003",
    outcome: "failed",
    config: {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "gsd-auto-retro",
      maxIssuesPerRun: 10,
    },
    findings: [pendingFinding],
    createIssue: () => ({ ok: false, error: "network unavailable" }),
    ensureLabel: () => ({ ok: true, data: undefined }),
    listIssuesByLabel: () => ({ ok: true, data: [] }),
  });

  const result = await fileRetrospectiveIssues({
    basePath: base,
    milestoneId: "M003",
    outcome: "failed",
    config: {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "gsd-auto-retro",
      maxIssuesPerRun: 10,
    },
    findings: [pendingFinding],
    createIssue: () => ({ ok: true, data: 43 }),
    ensureLabel: () => ({ ok: true, data: undefined }),
    listIssuesByLabel: () => ({ ok: true, data: [] }),
  });

  assert.deepEqual(result, { created: 1, pending: 0, skipped: 0 });
  const map = readIssueMap(join(base, ".gsd", "milestones", "M003", "M003-RETRO-ISSUES.json"));
  assert.equal(map?.records.length, 1);
  assert.equal(map?.records[0]?.status, "created");
  assert.equal(map?.records[0]?.issueNumber, 43);
});

test("fileRetrospectiveIssues records pending instead of creating when remote dedupe listing fails", async () => {
  const base = realpathSync(mkdtempSync(join(tmpdir(), "gsd-retro-file-")));
  mkdirSync(join(base, ".gsd", "milestones", "M004"), { recursive: true });
  let createCalls = 0;
  let ensureCalls = 0;

  const result = await fileRetrospectiveIssues({
    basePath: base,
    milestoneId: "M004",
    outcome: "stuck",
    config: {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "gsd-auto-retro",
      maxIssuesPerRun: 10,
    },
    findings: [makeFinding({ title: "List failure", fingerprint: "6".repeat(64) })],
    createIssue: () => {
      createCalls++;
      return { ok: true, data: 44 };
    },
    ensureLabel: () => {
      ensureCalls++;
      return { ok: true, data: undefined };
    },
    listIssuesByLabel: () => ({ ok: false, error: "gh rate limited" }),
  });

  assert.deepEqual(result, { created: 0, pending: 1, skipped: 0 });
  assert.equal(createCalls, 0);
  assert.equal(ensureCalls, 0);
  const map = readIssueMap(join(base, ".gsd", "milestones", "M004", "M004-RETRO-ISSUES.json"));
  assert.equal(map?.records[0]?.status, "pending");
  assert.match(map?.records[0]?.error ?? "", /could not list existing retrospective issues/);
});

test("fileRetrospectiveIssues skips map and remote fingerprints and caps created issues", async () => {
  const base = realpathSync(mkdtempSync(join(tmpdir(), "gsd-retro-file-")));
  const milestoneDir = join(base, ".gsd", "milestones", "M002");
  mkdirSync(milestoneDir, { recursive: true });

  const mapped = makeFinding({ title: "Mapped", fingerprint: "1".repeat(64) });
  const remote = makeFinding({ title: "Remote", fingerprint: "2".repeat(64) });
  const created = makeFinding({ title: "Created", fingerprint: "3".repeat(64) });
  const capped = makeFinding({ title: "Capped", fingerprint: "4".repeat(64) });
  const issueMapPath = join(milestoneDir, "M002-RETRO-ISSUES.json");
  writeIssueMap(issueMapPath, {
    version: 1,
    milestoneId: "M002",
    issueRepo: "skspade/gsd-pi",
    issueLabel: "gsd-auto-retro",
    records: [
      {
        fingerprint: mapped.fingerprint,
        title: mapped.title,
        category: mapped.category,
        status: "created",
        issueNumber: 41,
        issueUrl: "https://github.com/skspade/gsd-pi/issues/41",
        updatedAt: "2026-06-01T00:00:00.000Z",
      },
    ],
  });

  const createdTitles: string[] = [];
  let ensureLabelCalls = 0;
  const result = await fileRetrospectiveIssues({
    basePath: base,
    milestoneId: "M002",
    outcome: "failed",
    reason: "verification failed",
    config: {
      enabled: true,
      issueRepo: "skspade/gsd-pi",
      issueLabel: "gsd-auto-retro",
      maxIssuesPerRun: 1,
    },
    findings: [mapped, remote, created, capped],
    createIssue: (cwd, opts) => {
      assert.equal(cwd, base);
      createdTitles.push(opts.title);
      assert.match(opts.body, /Local retrospective: `\.gsd\/milestones\/M002\/M002-RETRO\.md`/);
      return { ok: true, data: 42 };
    },
    ensureLabel: () => {
      ensureLabelCalls++;
      return { ok: true, data: undefined };
    },
    listIssuesByLabel: () => ({
      ok: true,
      data: [
        {
          number: 40,
          title: "Existing remote",
          body: `Fingerprint: \`${remote.fingerprint}\``,
          url: "https://github.com/skspade/gsd-pi/issues/40",
        },
      ],
    }),
  });

  assert.deepEqual(result, { created: 1, pending: 0, skipped: 3 });
  assert.equal(ensureLabelCalls, 1);
  assert.deepEqual(createdTitles, ["[auto-retro][workflow-friction] Created"]);
  const map = readIssueMap(issueMapPath);
  assert.equal(map?.records.length, 2);
  assert.equal(map?.records[1]?.status, "created");
  assert.equal(map?.records[1]?.fingerprint, created.fingerprint);
});
